// Strategic assets — flow tier (港湾・物流 / 工場・製造 / エネルギー・資源 / チョークポイント).
// flow_busd  = annual economic flow tied to the site ($B, illustrative reference values).
// recovery_mo = assumed outage months if destroyed; flow loss = flow × (recovery/12) × damage fraction.
// deps       = approx. fraction of the flow serving each country (drives dependency arcs).
// cc         = nearest listed state for sites in unlisted countries (e.g. Qatar→AE, Panama→CO); informational only.
// Sources: UNCTAD / Lloyd's List, company reports, EIA/JODI, USGS — order-of-magnitude only.
const ASSETS = [

  // ---- port · 港湾・物流ハブ ----
  {
    id: "port-shanghai", cat: "port", cc: "CN",
    name_ja: "上海港（洋山深水港）", name_en: "Port of Shanghai (Yangshan)",
    lat: 30.63, lng: 122.06, r_km: 15,
    flow_busd: 1000, recovery_mo: 16,
    stat_ja: "年間4,900万TEU · 世界1位", stat_en: "49M TEU/yr · world #1",
    deps: { US: 0.18, JP: 0.07, DE: 0.06, KR: 0.05, NL: 0.04 },
    desc_ja: "洋山深水港と外高橋のコンテナ処理能力が喪失。世界最大の輸出ゲートが閉じ、東アジア発の海上物流網が数か月にわたり再編を強いられる。",
    desc_en: "Container handling at Yangshan and Waigaoqiao ceases. The world's largest export gateway closes, forcing months of rerouting across East Asian maritime logistics.",
    src_note: "Lloyd's List One Hundred Ports 2024",
  },
  {
    id: "port-ningbo-zhoushan", cat: "port", cc: "CN",
    name_ja: "寧波舟山港", name_en: "Port of Ningbo-Zhoushan",
    lat: 29.93, lng: 121.83, r_km: 15,
    flow_busd: 600, recovery_mo: 14,
    stat_ja: "3,300万TEU · 取扱量世界1位", stat_en: "33M TEU/yr · #1 by tonnage",
    deps: { US: 0.18, DE: 0.07, JP: 0.06, GB: 0.04 },
    desc_ja: "北侖・穿山のバース群と鉄鉱石・原油桟橋が機能停止。長江デルタの原材料供給と輸出が同時に寸断され、中国製造業の稼働率が急落する。",
    desc_en: "Berths at Beilun and Chuanshan plus iron-ore and crude jetties go offline. Raw-material inflows and exports for the Yangtze Delta are severed at once, cutting utilization across Chinese manufacturing.",
    src_note: "Lloyd's List/UNCTAD 2023",
  },
  {
    id: "port-singapore", cat: "port", cc: "SG",
    name_ja: "シンガポール港", name_en: "Port of Singapore",
    lat: 1.265, lng: 103.759, r_km: 12,
    flow_busd: 600, recovery_mo: 15,
    stat_ja: "3,900万TEU · 積替世界最大", stat_en: "39M TEU/yr · top transship hub",
    deps: { CN: 0.15, MY: 0.08, ID: 0.08, IN: 0.06, US: 0.06, TH: 0.04 },
    desc_ja: "パシルパンジャンの積替ヤードが消失。アジア〜欧州航路の接続網が崩れ、世界のコンテナ運航スケジュールが連鎖的に乱れる。",
    desc_en: "Pasir Panjang's transshipment yards are destroyed. Asia-Europe connectivity collapses and container schedules worldwide cascade into disorder.",
    src_note: "MPA Singapore / UNCTAD 2023",
  },
  {
    id: "port-yantian", cat: "port", cc: "CN",
    name_ja: "深圳港（塩田）", name_en: "Port of Shenzhen (Yantian)",
    lat: 22.577, lng: 114.271, r_km: 8,
    flow_busd: 500, recovery_mo: 12,
    stat_ja: "3,000万TEU · 対米輸出の主要門", stat_en: "30M TEU/yr · key US export gate",
    deps: { US: 0.25, GB: 0.06, DE: 0.06, NL: 0.05 },
    desc_ja: "塩田の深水バースが崩壊し、華南発の対米・対欧コンテナ輸出が停止。欧米小売の商戦向け在庫の供給線が断たれる。",
    desc_en: "Yantian's deep-water berths collapse, halting South China's container exports to the US and Europe. Supply lines feeding Western retail inventories are cut.",
    src_note: "Lloyd's List 2024 / port authority reports",
  },
  {
    id: "port-rotterdam", cat: "port", cc: "NL",
    name_ja: "ロッテルダム港（マースフラクテ）", name_en: "Port of Rotterdam (Maasvlakte)",
    lat: 51.955, lng: 4.035, r_km: 15,
    flow_busd: 500, recovery_mo: 15,
    stat_ja: "1,400万TEU · 欧州最大", stat_en: "14M TEU/yr · Europe #1",
    deps: { DE: 0.3, BE: 0.08, FR: 0.07, GB: 0.06, PL: 0.04 },
    desc_ja: "マースフラクテのコンテナ・石油ターミナルが壊滅。欧州最大の玄関口が閉じ、ドイツ工業地帯への原材料供給が週単位で細る。",
    desc_en: "Container and petroleum terminals at Maasvlakte are destroyed. Europe's largest gateway closes, starving German industry of inputs within weeks.",
    src_note: "Port of Rotterdam annual report 2023",
  },
  {
    id: "port-la-long-beach", cat: "port", cc: "US",
    name_ja: "ロサンゼルス／ロングビーチ港", name_en: "Ports of LA / Long Beach",
    lat: 33.742, lng: -118.24, r_km: 12,
    flow_busd: 450, recovery_mo: 14,
    stat_ja: "1,700万TEU · 米輸入の4割", stat_en: "17M TEU/yr · 40% of US imports",
    deps: { CN: 0.45, JP: 0.08, KR: 0.06, VN: 0.06, TW: 0.04 },
    desc_ja: "サンペドロ湾両港のガントリーと操車場が壊滅。米国のコンテナ輸入の約4割が行き場を失い、小売・製造在庫が数週間で逼迫する。",
    desc_en: "Gantries and rail yards across San Pedro Bay are destroyed. Roughly 40% of US container imports lose their entry point; retail and manufacturing inventories tighten within weeks.",
    src_note: "POLA/POLB annual reports 2023",
  },
  {
    id: "port-qingdao", cat: "port", cc: "CN",
    name_ja: "青島港（前湾）", name_en: "Port of Qingdao (Qianwan)",
    lat: 36.03, lng: 120.23, r_km: 10,
    flow_busd: 400, recovery_mo: 12,
    stat_ja: "2,600万TEU · 世界5位", stat_en: "26M TEU/yr · world #5",
    deps: { US: 0.12, KR: 0.1, JP: 0.08, DE: 0.05 },
    desc_ja: "前湾コンテナターミナルと鉱石桟橋が使用不能。華北の輸出と日韓向けフィーダー網が寸断される。",
    desc_en: "Qianwan container terminals and ore berths are knocked out. North China's exports and feeder links to Japan and Korea are severed.",
    src_note: "Lloyd's List 2024",
  },
  {
    id: "port-busan", cat: "port", cc: "KR",
    name_ja: "釜山港（新港）", name_en: "Port of Busan (New Port)",
    lat: 35.077, lng: 128.834, r_km: 10,
    flow_busd: 400, recovery_mo: 13,
    stat_ja: "2,300万TEU · 世界7位", stat_en: "23M TEU/yr · world #7",
    deps: { CN: 0.15, US: 0.15, JP: 0.1, VN: 0.04 },
    desc_ja: "釜山新港のターミナル群が機能停止。韓国輸出の7割超と北東アジアの積替機能が失われ、日中韓の物流が玉突きで滞る。",
    desc_en: "Terminals at Busan New Port go dark. Over 70% of Korean exports and Northeast Asia's transshipment capacity vanish, jamming logistics across the region.",
    src_note: "BPA / Lloyd's List 2024",
  },
  {
    id: "port-hong-kong-air", cat: "port", cc: "HK",
    name_ja: "香港国際空港（貨物）", name_en: "Hong Kong Intl Airport (cargo)",
    lat: 22.308, lng: 113.918, r_km: 6,
    flow_busd: 400, recovery_mo: 14,
    stat_ja: "航空貨物430万トン · 世界1位", stat_en: "4.3Mt air cargo/yr · world #1",
    deps: { CN: 0.35, US: 0.15, TW: 0.06, JP: 0.05, SG: 0.03 },
    desc_ja: "チェクラップコクの貨物ターミナル群が消失。半導体・精密機器を運ぶ世界最大の航空貨物結節点が失われ、高付加価値貿易が数か月停滞する。",
    desc_en: "Cargo terminals at Chek Lap Kok are destroyed. The world's busiest air-freight node for semiconductors and precision goods vanishes, stalling high-value trade for months.",
    src_note: "ACI / HKIA 2023",
  },
  {
    id: "port-antwerp-bruges", cat: "port", cc: "BE",
    name_ja: "アントワープ＝ブルージュ港", name_en: "Port of Antwerp-Bruges",
    lat: 51.288, lng: 4.287, r_km: 12,
    flow_busd: 350, recovery_mo: 13,
    stat_ja: "1,300万TEU · 欧州2位", stat_en: "13M TEU/yr · Europe #2",
    deps: { DE: 0.2, FR: 0.12, NL: 0.1, GB: 0.05 },
    desc_ja: "シェルデ川沿いのドック群と化学品クラスターが機能停止。欧州の化学・自動車物流の中核が失われ、域内サプライチェーンが混乱する。",
    desc_en: "Docks and the chemical cluster along the Scheldt go offline. A core node of European chemical and automotive logistics disappears, disrupting continental supply chains.",
    src_note: "Port of Antwerp-Bruges 2023",
  },
  {
    id: "port-memphis-air", cat: "port", cc: "US",
    name_ja: "メンフィス空港（FedExスーパーハブ）", name_en: "Memphis Intl (FedEx SuperHub)",
    lat: 35.042, lng: -89.977, r_km: 6,
    flow_busd: 300, recovery_mo: 12,
    stat_ja: "貨物400万トン · FedEx中枢", stat_en: "4Mt cargo/yr · FedEx SuperHub",
    deps: { CA: 0.08, MX: 0.06, CN: 0.05, GB: 0.03 },
    desc_ja: "フェデックスの仕分け中枢と滑走路が使用不能。米国内の翌日配送網が崩れ、医薬品・部品の緊急物流が全国規模で停滞する。",
    desc_en: "FedEx's sorting core and runways are knocked out. The US overnight delivery network collapses, stalling urgent shipments of medicines and parts nationwide.",
    src_note: "ACI air cargo rankings 2023",
  },
  {
    id: "port-jebel-ali", cat: "port", cc: "AE",
    name_ja: "ジュベル・アリ港", name_en: "Port of Jebel Ali",
    lat: 25.011, lng: 55.061, r_km: 10,
    flow_busd: 250, recovery_mo: 12,
    stat_ja: "1,400万TEU · 中東最大", stat_en: "14M TEU/yr · Middle East #1",
    deps: { SA: 0.12, IN: 0.1, EG: 0.04, PK: 0.04 },
    desc_ja: "ジュベル・アリのバースとフリーゾーンが使用不能。中東・南アジア向け再輸出網の中枢が失われ、湾岸の消費財供給が滞る。",
    desc_en: "Jebel Ali's berths and free zone are knocked out. The hub of re-export networks serving the Middle East and South Asia is lost, choking consumer-goods supply across the Gulf.",
    src_note: "DP World / Lloyd's List 2024",
  },
  {
    id: "port-ny-nj", cat: "port", cc: "US",
    name_ja: "ニューヨーク・ニュージャージー港", name_en: "Port of New York / New Jersey",
    lat: 40.684, lng: -74.145, r_km: 10,
    flow_busd: 250, recovery_mo: 12,
    stat_ja: "950万TEU · 東海岸最大", stat_en: "9.5M TEU/yr · East Coast #1",
    deps: { CN: 0.25, DE: 0.08, IN: 0.06, IT: 0.05 },
    desc_ja: "ニューアーク＝エリザベス埠頭と周辺インフラが使用不能。米東海岸最大の玄関口が閉じ、北東部の消費財供給が細る。",
    desc_en: "Port Newark-Elizabeth and surrounding infrastructure are knocked out. The East Coast's largest gateway closes, thinning consumer-goods supply to the Northeast.",
    src_note: "PANYNJ 2023",
  },
  {
    id: "port-klang", cat: "port", cc: "MY",
    name_ja: "ポートクラン（ウェストポーツ）", name_en: "Port Klang (Westports)",
    lat: 2.944, lng: 101.316, r_km: 8,
    flow_busd: 200, recovery_mo: 11,
    stat_ja: "1,400万TEU · 世界11位", stat_en: "14M TEU/yr · world #11",
    deps: { CN: 0.15, SG: 0.08, US: 0.08, IN: 0.05 },
    desc_ja: "ウェストポーツのターミナルが崩壊。マラッカ海峡航路の主要中継点が失われ、東南アジアのフィーダー網が再編を迫られる。",
    desc_en: "Westports' terminals collapse. A key relay on the Malacca route is lost, forcing a redesign of Southeast Asian feeder networks.",
    src_note: "Westports Holdings / Lloyd's List 2024",
  },
  {
    id: "port-kaohsiung", cat: "port", cc: "TW",
    name_ja: "高雄港", name_en: "Port of Kaohsiung",
    lat: 22.575, lng: 120.297, r_km: 9,
    flow_busd: 200, recovery_mo: 12,
    stat_ja: "900万TEU · 台湾貨物の6割", stat_en: "9M TEU/yr · 60% of TW cargo",
    deps: { CN: 0.15, US: 0.12, JP: 0.08, HK: 0.05 },
    desc_ja: "高雄港のコンテナ埠頭が機能停止。台湾の海上貿易の過半が止まり、電子部品・素材の供給網に波及する。",
    desc_en: "Kaohsiung's container wharves go offline. The majority of Taiwan's seaborne trade halts, rippling through electronics component and materials supply.",
    src_note: "TIPC / Lloyd's List 2024",
  },
  {
    id: "port-duisburg-rail", cat: "port", cc: "DE",
    name_ja: "デュースブルク内陸港", name_en: "Port of Duisburg (duisport)",
    lat: 51.452, lng: 6.732, r_km: 6,
    flow_busd: 80, recovery_mo: 12,
    stat_ja: "中欧班列の欧州終点 · 400万TEU", stat_en: "China-EU rail terminus · 4M TEU",
    deps: { CN: 0.3, NL: 0.12, PL: 0.06, CZ: 0.04 },
    desc_ja: "ライン川ターミナルと中欧班列の操車場が機能停止。中国〜欧州の陸上動脈の終点が失われ、ルール工業地帯の物流が寸断される。",
    desc_en: "Rhine terminals and the China-Europe rail yards go offline. The western terminus of the overland artery to China is lost, severing logistics across the Ruhr.",
    src_note: "duisport reports / China Railway Express data",
  },

  // ---- factory · 工場・製造クラスタ ----
  {
    id: "factory-shenzhen-dongguan-belt", cat: "factory", cc: "CN",
    name_ja: "深圳・東莞 電子製造ベルト", name_en: "Shenzhen-Dongguan Electronics Belt",
    lat: 22.9, lng: 113.89, r_km: 10,
    flow_busd: 200, recovery_mo: 24,
    stat_ja: "世界の電子製造ベルト", stat_en: "World's electronics belt",
    deps: { US: 0.25, DE: 0.08, JP: 0.07, GB: 0.05, IN: 0.05, NL: 0.04 },
    desc_ja: "世界の電子機器製造が集中する珠江デルタのベルトが消失。部品から完成品までの供給網が寸断され、家電・通信機器・PC周辺機器の世界供給が全面的に縮小する。",
    desc_en: "The Pearl River Delta belt where the world's electronics manufacturing concentrates is wiped out. Supply chains from components to finished goods are severed, shrinking global supply of consumer, telecom and PC hardware.",
    src_note: "Guangdong stats; China Customs",
  },
  {
    id: "factory-suzhou-kunshan", cat: "factory", cc: "CN",
    name_ja: "蘇州・昆山 電子クラスタ", name_en: "Suzhou-Kunshan Electronics Cluster",
    lat: 31.3876, lng: 120.9812, r_km: 8,
    flow_busd: 120, recovery_mo: 20,
    stat_ja: "ノートPC世界供給の要", stat_en: "Key laptop supply hub",
    deps: { US: 0.28, DE: 0.08, JP: 0.07, GB: 0.05, NL: 0.04 },
    desc_ja: "世界のノートPCと電子部品の一大供給地が停止。基板・完成品の生産が絶たれ、PC・サーバー市場の在庫が枯渇して情報インフラの更新が遅延する。",
    desc_en: "A prime supply base for the world's laptops and electronic components halts. Board and finished-goods output is cut, draining PC and server inventories and delaying IT infrastructure refresh.",
    src_note: "Jiangsu/Kunshan stats bureau",
  },
  {
    id: "factory-foxconn-zhengzhou", cat: "factory", cc: "CN",
    name_ja: "フォックスコン鄭州（iPhone City）", name_en: "Foxconn Zhengzhou (iPhone City)",
    lat: 34.5308, lng: 113.8398, r_km: 6,
    flow_busd: 90, recovery_mo: 18,
    stat_ja: "iPhone年産1.5億台規模", stat_en: "~150M iPhones/yr",
    deps: { US: 0.4, JP: 0.07, GB: 0.05, DE: 0.05, FR: 0.04 },
    desc_ja: "世界のiPhone生産の半分を担う組立都市が停止。年1億台超の完成品供給が絶たれ、年末商戦を軸とする世界のスマートフォン流通が数か月にわたり滞る。",
    desc_en: "The assembly city that builds half the world's iPhones stops. Output of over a hundred million finished units a year is cut, choking global smartphone distribution for months around the peak season.",
    src_note: "Company reports; press estimates",
  },
  {
    id: "factory-toyota-city", cat: "factory", cc: "JP",
    name_ja: "豊田市（トヨタ本拠工場群）", name_en: "Toyota City (Toyota home plants)",
    lat: 35.0826, lng: 137.156, r_km: 8,
    flow_busd: 70, recovery_mo: 20,
    stat_ja: "トヨタ本拠地 · 自動車中枢", stat_en: "Toyota HQ · auto core",
    deps: { US: 0.35, CN: 0.08, AU: 0.06, CA: 0.05, GB: 0.04 },
    desc_ja: "トヨタの本拠工場群とジャストインタイム部品網が消失。国内完成車生産と世界の系列サプライヤーへの部品供給が同時に止まり、世界の自動車生産が連鎖的に減速する。",
    desc_en: "Toyota's home plant complex and its just-in-time parts network vanish. Domestic vehicle output and parts to affiliated suppliers worldwide stop at once, cascading into slower global auto production.",
    src_note: "Toyota FY report; JAMA",
  },
  {
    id: "factory-basel-pharma", cat: "factory", cc: "CH",
    name_ja: "バーゼル製薬クラスタ（ロシュ・ノバルティス）", name_en: "Basel Pharma Cluster (Roche & Novartis)",
    lat: 47.561, lng: 7.59, r_km: 5,
    flow_busd: 60, recovery_mo: 24,
    stat_ja: "ロシュ・ノバルティス本拠", stat_en: "Roche & Novartis home",
    deps: { US: 0.35, DE: 0.1, JP: 0.08, FR: 0.06, GB: 0.05, IT: 0.04 },
    desc_ja: "ロシュとノバルティスを核とする世界有数の製薬集積地が消失。基幹医薬品と原薬の供給が細り、がん・免疫・慢性疾患領域の治療供給が世界規模で不安定化する。",
    desc_en: "The world-leading pharma cluster anchored by Roche and Novartis is wiped out. Supply of key drugs and active ingredients thins, destabilizing treatment for cancer, immune and chronic diseases worldwide.",
    src_note: "Roche/Novartis reports; Interpharma",
  },
  {
    id: "factory-hyundai-ulsan", cat: "factory", cc: "KR",
    name_ja: "現代自動車 蔚山工業団地", name_en: "Hyundai Ulsan Industrial Complex",
    lat: 35.5127, lng: 129.418, r_km: 8,
    flow_busd: 55, recovery_mo: 20,
    stat_ja: "世界最大の単一車工場", stat_en: "World's largest single plant",
    deps: { US: 0.3, DE: 0.06, GB: 0.05, AU: 0.05, CA: 0.04 },
    desc_ja: "世界最大の単一自動車工場と隣接する重工業群が消失。完成車と船舶の生産が同時に止まり、韓国の輸出とグローバルな自動車供給が大きく減退する。",
    desc_en: "The world's largest single auto plant and the adjacent heavy-industry complex are wiped out. Vehicle and shipbuilding output stop together, sharply cutting Korean exports and global vehicle supply.",
    src_note: "Hyundai Motor report; KAMA",
  },
  {
    id: "factory-tsmc-hsinchu", cat: "factory", cc: "TW",
    name_ja: "TSMC新竹（本社・GigaFab）", name_en: "TSMC Hsinchu (HQ & GigaFab)",
    lat: 24.7738, lng: 120.9967, r_km: 6,
    flow_busd: 50, recovery_mo: 42,
    stat_ja: "TSMC本社 · 先端ロジック中枢", stat_en: "TSMC HQ · leading-edge logic",
    deps: { US: 0.45, CN: 0.12, JP: 0.08, KR: 0.05, DE: 0.04 },
    desc_ja: "世界最先端ロジック半導体の設計中枢と量産ラインが同時に消失。スマートフォンからデータセンターまで先端チップ供給が数年単位で寸断され、電子機器の世代更新が世界規模で停止する。",
    desc_en: "The design core and volume lines for the world's most advanced logic chips vanish at once. Leading-edge silicon for everything from phones to data centers is severed for years, halting the global refresh of electronics.",
    src_note: "TSMC annual report 2023; SIA",
  },
  {
    id: "factory-samsung-pyeongtaek", cat: "factory", cc: "KR",
    name_ja: "サムスン平沢キャンパス", name_en: "Samsung Pyeongtaek Campus",
    lat: 37.005, lng: 127.055, r_km: 5,
    flow_busd: 45, recovery_mo: 40,
    stat_ja: "世界最大級のメモリ工場", stat_en: "World's largest memory fab",
    deps: { CN: 0.35, US: 0.25, TW: 0.05, JP: 0.05, DE: 0.05 },
    desc_ja: "世界最大級のメモリ量産キャンパスが消失。DRAMとNANDの供給が急減し、サーバー・スマートフォン・データセンター向け記憶装置の価格が急騰、電子機器全般の生産が減速する。",
    desc_en: "The world's largest memory campus is wiped out. DRAM and NAND supply collapses, spiking memory prices for servers, phones and data centers and slowing electronics production worldwide.",
    src_note: "Samsung DS reports; TrendForce",
  },
  {
    id: "factory-vw-wolfsburg", cat: "factory", cc: "DE",
    name_ja: "フォルクスワーゲン・ヴォルフスブルク", name_en: "Volkswagen Wolfsburg",
    lat: 52.4318, lng: 10.7997, r_km: 6,
    flow_busd: 45, recovery_mo: 20,
    stat_ja: "世界最大級の自動車工場", stat_en: "World's largest car plant",
    deps: { CN: 0.25, US: 0.12, GB: 0.07, FR: 0.06, IT: 0.05 },
    desc_ja: "世界最大級の単一自動車工場が停止。欧州の量販車生産が急減し、部品供給網を通じて欧州自動車産業全体の稼働が落ち込む。",
    desc_en: "One of the world's largest single car plants halts. Europe's volume vehicle output drops sharply, dragging down the whole European auto sector through its parts network.",
    src_note: "Volkswagen AG report",
  },
  {
    id: "factory-tsmc-tainan-fab18", cat: "factory", cc: "TW",
    name_ja: "TSMC台南（Fab 18・南部科学園区）", name_en: "TSMC Tainan (Fab 18, STSP)",
    lat: 23.108, lng: 120.284, r_km: 6,
    flow_busd: 40, recovery_mo: 48,
    stat_ja: "3/5nm量産 · GigaFab", stat_en: "N3/N5 volume · GigaFab",
    deps: { US: 0.45, CN: 0.15, JP: 0.07, KR: 0.05, NL: 0.03 },
    desc_ja: "3〜5nm世代を独占的に量産するギガファブが停止。AI半導体と最新スマートフォン向けSoCの供給が絶たれ、世界のAIインフラ増強計画が一斉に凍結する。",
    desc_en: "The GigaFab that alone volume-produces the 3-5nm generation goes dark. Supply of AI accelerators and flagship smartphone SoCs is cut, freezing the world's AI buildout at once.",
    src_note: "TSMC annual report 2023",
  },
  {
    id: "factory-airbus-toulouse", cat: "factory", cc: "FR",
    name_ja: "エアバス・トゥールーズ（ブラニャック）", name_en: "Airbus Toulouse (Blagnac)",
    lat: 43.635, lng: 1.362, r_km: 5,
    flow_busd: 40, recovery_mo: 24,
    stat_ja: "エアバス最終組立拠点", stat_en: "Airbus final assembly hub",
    deps: { CN: 0.18, US: 0.15, IN: 0.1, AE: 0.06, GB: 0.05, TR: 0.04 },
    desc_ja: "エアバス旅客機の最終組立中枢が停止。新造機の引き渡しが数年単位で滞り、世界の航空会社の機材更新計画と航空輸送の増強が凍結する。",
    desc_en: "Airbus's final-assembly core for airliners halts. New-aircraft deliveries stall for years, freezing airlines' fleet renewals and the expansion of global air transport.",
    src_note: "Airbus annual report 2023",
  },
  {
    id: "factory-sk-hynix-icheon", cat: "factory", cc: "KR",
    name_ja: "SKハイニックス利川", name_en: "SK Hynix Icheon",
    lat: 37.244, lng: 127.462, r_km: 5,
    flow_busd: 30, recovery_mo: 36,
    stat_ja: "DRAM/HBMの主力拠点", stat_en: "Main DRAM & HBM site",
    deps: { US: 0.3, CN: 0.3, TW: 0.06, JP: 0.05, DE: 0.04 },
    desc_ja: "DRAMと生成AI向けHBMの主力拠点が停止。高帯域メモリの供給が細り、AIアクセラレータの量産計画が滞って世界のAI投資が減速する。",
    desc_en: "The main site for DRAM and AI-grade HBM halts. High-bandwidth memory supply thins, stalling AI accelerator production and slowing the world's AI investment.",
    src_note: "SK Hynix reports; TrendForce",
  },
  {
    id: "factory-asml-veldhoven", cat: "factory", cc: "NL",
    name_ja: "ASMLフェルトホーフェン", name_en: "ASML Veldhoven",
    lat: 51.4181, lng: 5.3999, r_km: 4,
    flow_busd: 30, recovery_mo: 48,
    stat_ja: "EUV露光を独占供給", stat_en: "Sole EUV lithography source",
    deps: { TW: 0.35, KR: 0.2, US: 0.15, CN: 0.15, JP: 0.05 },
    desc_ja: "EUV露光装置を世界で唯一量産する拠点が消失。最先端半導体の新規増産手段が断たれ、以後数年、世界のロジック・メモリ増設計画がすべて停止する。",
    desc_en: "The only site on Earth that builds EUV lithography machines is destroyed. The sole means of expanding leading-edge chip capacity is gone, halting every advanced logic and memory buildout for years.",
    src_note: "ASML annual report 2023",
  },
  {
    id: "factory-boeing-everett", cat: "factory", cc: "US",
    name_ja: "ボーイング・エバレット", name_en: "Boeing Everett",
    lat: 47.9186, lng: -122.2799, r_km: 4,
    flow_busd: 25, recovery_mo: 24,
    stat_ja: "世界最大の建屋 · 広胴機", stat_en: "World's largest building · widebodies",
    deps: { AE: 0.12, CN: 0.12, JP: 0.08, GB: 0.06, IN: 0.05 },
    desc_ja: "世界最大の建屋を擁するボーイングの広胴機組立拠点が消失。長距離旅客機と貨物機の新造が止まり、世界の長距離航空網と航空貨物の拡張計画が停滞する。",
    desc_en: "Boeing's widebody assembly site, housed in the world's largest building, is destroyed. Production of long-haul airliners and freighters stops, stalling expansion of global long-haul networks and air cargo.",
    src_note: "Boeing 10-K 2023",
  },
  {
    id: "factory-intel-chandler-ocotillo", cat: "factory", cc: "US",
    name_ja: "インテル・オコティージョ（アリゾナ州チャンドラー）", name_en: "Intel Ocotillo (Chandler, AZ)",
    lat: 33.235, lng: -111.905, r_km: 5,
    flow_busd: 20, recovery_mo: 36,
    stat_ja: "米国先端ロジック拠点", stat_en: "US leading-edge logic hub",
    deps: { CN: 0.25, DE: 0.08, JP: 0.07, GB: 0.05, KR: 0.05 },
    desc_ja: "米国内で最大級の先端ロジック量産拠点が停止。サーバー・PC向けプロセッサの供給が細り、西側の半導体自給計画が大きく後退する。",
    desc_en: "The largest US advanced-logic manufacturing site halts. Processor supply for servers and PCs thins, setting back the West's push for domestic chip self-sufficiency.",
    src_note: "Intel 10-K 2023",
  },

  // ---- energy · エネルギー・資源 ----
  {
    id: "energy-abqaiq", cat: "energy", cc: "SA",
    name_ja: "アブカイク原油処理施設", name_en: "Abqaiq Processing Facility",
    lat: 25.94, lng: 49.67, r_km: 6,
    flow_busd: 180, recovery_mo: 18,
    stat_ja: "原油処理 日量約700万バレル", stat_en: "~7M bbl/day processing hub",
    deps: { CN: 0.25, JP: 0.15, IN: 0.12, KR: 0.1, US: 0.05 },
    desc_ja: "世界最大の原油処理・安定化施設が消失。サウジ輸出原油の大半が精製前段階で滞留し、日量数百万バレルの供給が長期途絶する。",
    desc_en: "The world's largest crude processing and stabilization plant is destroyed. Most Saudi export crude stalls before shipment, cutting several million bbl/day for an extended period.",
    src_note: "EIA/Aramco disclosures",
  },
  {
    id: "energy-ras-tanura", cat: "energy", cc: "SA",
    name_ja: "ラス・タヌラ石油積出基地", name_en: "Ras Tanura Oil Terminal",
    lat: 26.64, lng: 50.16, r_km: 7,
    flow_busd: 150, recovery_mo: 14,
    stat_ja: "石油積出 日量約650万バレル", stat_en: "~6.5M bbl/day export terminal",
    deps: { CN: 0.25, JP: 0.15, IN: 0.12, KR: 0.1, US: 0.05 },
    desc_ja: "世界最大級の石油積出ターミナルが機能停止。ペルシャ湾からの原油輸出動脈が断たれ、東アジア向けタンカー供給が数か月単位で細る。",
    desc_en: "The world's largest oil export terminal ceases operation. The Gulf's crude export artery is severed, thinning tanker supply to East Asia for months.",
    src_note: "EIA/JODI",
  },
  {
    id: "energy-ghawar", cat: "energy", cc: "SA",
    name_ja: "ガワール油田", name_en: "Ghawar Oil Field",
    lat: 25.43, lng: 49.62, r_km: 45,
    flow_busd: 100, recovery_mo: 18,
    stat_ja: "産油量 日量約380万バレル", stat_en: "~3.8M bbl/day · largest field",
    deps: { CN: 0.25, JP: 0.15, IN: 0.15, KR: 0.1, US: 0.05 },
    desc_ja: "世界最大の在来型油田が操業停止。日量約380万バレルの原油供給が数か月消失し、アジアの製油所稼働と海上原油価格が同時に崩れる。",
    desc_en: "The world's largest conventional oilfield goes offline. Roughly 3.8M bbl/day of crude vanishes for months, breaking Asian refinery runs and spiking seaborne crude prices.",
    src_note: "EIA/Aramco disclosures",
  },
  {
    id: "energy-jurong-island", cat: "energy", cc: "SG",
    name_ja: "ジュロン島石化コンビナート", name_en: "Jurong Island Petrochemical Hub",
    lat: 1.26, lng: 103.7, r_km: 7,
    flow_busd: 80, recovery_mo: 20,
    stat_ja: "アジアの石化・製油集積地", stat_en: "Asia's petrochem hub",
    deps: { CN: 0.15, ID: 0.1, MY: 0.08, AU: 0.08, IN: 0.05, JP: 0.05 },
    desc_ja: "アジアの石化・製油集積地ジュロン島が消失。地域の燃料・化学品の中継供給が断たれ、東南アジアの生産網が広範に停止する。",
    desc_en: "Jurong Island, Asia's petrochemical and refining cluster, is destroyed. Regional fuel and chemical relay supply is cut, broadly halting Southeast Asian production networks.",
    src_note: "EDB/IEA",
  },
  {
    id: "energy-port-hedland", cat: "energy", cc: "AU",
    name_ja: "ポートヘッドランド鉄鉱石港(ピルバラ)", name_en: "Port Hedland Iron Ore (Pilbara)",
    lat: -20.31, lng: 118.58, r_km: 10,
    flow_busd: 65, recovery_mo: 12,
    stat_ja: "鉄鉱石積出 年約5.5億トン", stat_en: "~550 Mt/yr iron ore · #1",
    deps: { CN: 0.8, JP: 0.08, KR: 0.05 },
    desc_ja: "世界最大の鉄鉱石積出港が機能停止。年約5.5億トンの供給が絶たれ、中国の高炉稼働と世界の鋼材供給が数か月にわたり縮小する。",
    desc_en: "The world's largest iron-ore export port ceases operation. Some 550 Mt/yr is cut, shrinking Chinese blast-furnace runs and global steel supply for months.",
    src_note: "Pilbara Ports Authority",
  },
  {
    id: "energy-kharg-island", cat: "energy", cc: "IR",
    name_ja: "ハルク島原油積出基地", name_en: "Kharg Island Oil Terminal",
    lat: 29.23, lng: 50.32, r_km: 6,
    flow_busd: 60, recovery_mo: 15,
    stat_ja: "イラン原油輸出の約9割", stat_en: "~90% of Iran's crude exports",
    deps: { CN: 0.8, IN: 0.05, AE: 0.03, TR: 0.02 },
    desc_ja: "イラン原油輸出の約9割を担う積出島が消失。中国向けを中心とした日量約200万バレルの供給が絶たれ、制裁下の代替調達が急騰する。",
    desc_en: "The island terminal handling ~90% of Iran's crude exports is wiped out. Some 2M bbl/day, mostly China-bound, is cut, and sanction-era substitute barrels surge.",
    src_note: "EIA/tanker tracking",
  },
  {
    id: "energy-jamnagar", cat: "energy", cc: "IN",
    name_ja: "ジャムナガル製油所", name_en: "Jamnagar Refinery",
    lat: 22.34, lng: 69.85, r_km: 8,
    flow_busd: 55, recovery_mo: 20,
    stat_ja: "世界最大の製油複合施設", stat_en: "world's largest refinery",
    deps: { US: 0.1, NL: 0.08, GB: 0.05, SG: 0.05, AE: 0.05 },
    desc_ja: "世界最大の製油複合施設が停止。日量約140万バレルの精製能力が失われ、インド国内供給と欧米・アフリカ向け製品輸出が同時に途絶する。",
    desc_en: "The world's largest refining complex halts. Some 1.4M bbl/day of capacity is lost, cutting India's domestic supply and product exports to the West and Africa at once.",
    src_note: "Reliance reports/IEA",
  },
  {
    id: "energy-ras-laffan", cat: "energy", cc: "AE",
    name_ja: "ラスラファンLNG基地(カタール)", name_en: "Ras Laffan LNG (Qatar)",
    lat: 25.91, lng: 51.58, r_km: 8,
    flow_busd: 50, recovery_mo: 20,
    stat_ja: "LNG年約7,700万トン 世界最大", stat_en: "~77 Mt/yr LNG · world's top",
    deps: { CN: 0.2, KR: 0.15, IN: 0.12, JP: 0.1, IT: 0.05, GB: 0.05 },
    desc_ja: "世界最大級のLNG輸出基地(カタール)が停止。年約7,700万トンの液化能力が失われ、アジアと欧州のガス在庫と電力価格が連鎖的に悪化する。",
    desc_en: "The world's largest LNG export hub (Qatar) halts. Some 77 Mt/yr of liquefaction is lost, cascading into Asian and European gas inventories and power prices.",
    src_note: "GIIGNL/QatarEnergy",
  },
  {
    id: "energy-sabine-pass", cat: "energy", cc: "US",
    name_ja: "サビンパスLNG基地", name_en: "Sabine Pass LNG",
    lat: 29.74, lng: -93.87, r_km: 6,
    flow_busd: 18, recovery_mo: 18,
    stat_ja: "米国最大のLNG輸出基地", stat_en: "largest US LNG export terminal",
    deps: { NL: 0.15, FR: 0.1, GB: 0.1, KR: 0.1, JP: 0.08, CN: 0.05 },
    desc_ja: "米国最大のLNG輸出基地が消失。欧州向けを中心とする液化ガス供給が数か月止まり、大西洋を挟んだガス需給の綱渡りが崩れる。",
    desc_en: "The largest US LNG export terminal is destroyed. Europe-bound liquefied gas stops for months, collapsing the transatlantic supply balance.",
    src_note: "EIA/Cheniere reports",
  },
  {
    id: "energy-norilsk", cat: "energy", cc: "RU",
    name_ja: "ノリリスク・ニッケル/パラジウム鉱山", name_en: "Norilsk Nickel-Palladium",
    lat: 69.35, lng: 88.2, r_km: 18,
    flow_busd: 12, recovery_mo: 20,
    stat_ja: "世界最大のパラジウム産地", stat_en: "#1 palladium · Ni/Pd source",
    deps: { CN: 0.2, DE: 0.15, US: 0.1, JP: 0.08, GB: 0.05 },
    desc_ja: "世界最大のパラジウム・ニッケル産地ノリリスクが操業停止。触媒・電池向け金属供給が細り、自動車と航空の生産計画が世界規模で狂う。",
    desc_en: "Norilsk, the world's top palladium and nickel source, halts. Catalyst and battery metal supply thins, disrupting auto and aerospace production plans worldwide.",
    src_note: "USGS/Nornickel reports",
  },
  {
    id: "energy-yamal-sabetta", cat: "energy", cc: "RU",
    name_ja: "ヤマルLNG・サベッタ", name_en: "Yamal LNG / Sabetta",
    lat: 71.27, lng: 72.06, r_km: 6,
    flow_busd: 10, recovery_mo: 24,
    stat_ja: "北極圏LNG 年約1,750万トン", stat_en: "Arctic LNG · ~17.5 Mt/yr",
    deps: { CN: 0.25, FR: 0.1, ES: 0.08, BE: 0.08, NL: 0.05 },
    desc_ja: "北極圏の液化基地サベッタが機能停止。年約1,750万トンのLNGと北極海航路経由の輸送が止まり、寒冷期の欧州・中国調達が逼迫する。",
    desc_en: "The Arctic Sabetta liquefaction plant goes offline. Some 17.5 Mt/yr of LNG and its Northern Sea Route shipments halt, tightening cold-season supply to Europe and China.",
    src_note: "GIIGNL/Novatek reports",
  },
  {
    id: "energy-karratha-nws", cat: "energy", cc: "AU",
    name_ja: "ノースウェスト・シェルフLNG(カラサ)", name_en: "North West Shelf LNG (Karratha)",
    lat: -20.62, lng: 116.77, r_km: 6,
    flow_busd: 10, recovery_mo: 18,
    stat_ja: "豪LNG 年約1,690万トン", stat_en: "~16.9 Mt/yr LNG · Australia",
    deps: { JP: 0.5, CN: 0.2, KR: 0.1 },
    desc_ja: "豪州最大級のLNG拠点カラサが停止。年約1,690万トンの供給が絶たれ、長期契約に依存する日本・韓国の発電用ガスが不足する。",
    desc_en: "Australia's major Karratha LNG hub halts. Some 16.9 Mt/yr is cut, starving Japan and Korea of contracted power-generation gas.",
    src_note: "GIIGNL/Woodside reports",
  },
  {
    id: "energy-escondida", cat: "energy", cc: "CL",
    name_ja: "エスコンディダ銅鉱山", name_en: "Escondida Copper Mine",
    lat: -24.27, lng: -69.07, r_km: 15,
    flow_busd: 10, recovery_mo: 18,
    stat_ja: "世界最大の銅鉱山 年110万t", stat_en: "#1 copper mine · ~1.1 Mt/yr",
    deps: { CN: 0.4, JP: 0.15, KR: 0.1, IN: 0.05 },
    desc_ja: "世界最大の銅鉱山が操業停止。年約110万トンの銅精鉱供給が消え、中国の製錬と世界の電線・EV配線向け銅相場が急騰する。",
    desc_en: "The world's largest copper mine halts. Roughly 1.1 Mt/yr of concentrate disappears, spiking copper for Chinese smelters and global wiring and EV supply.",
    src_note: "USGS/BHP reports",
  },
  {
    id: "energy-three-gorges", cat: "energy", cc: "CN",
    name_ja: "三峡ダム", name_en: "Three Gorges Dam",
    lat: 30.823, lng: 111.003, r_km: 12,
    flow_busd: 8, recovery_mo: 48,
    stat_ja: "世界最大の水力 2,250万kW", stat_en: "largest hydro · 22.5 GW",
    deps: { US: 0.15, JP: 0.08, DE: 0.06, GB: 0.04, KR: 0.04 },
    desc_ja: "世界最大の水力発電ダムが決壊。2,250万kWの電力が失われ、長江下流の広域が浸水し、中国中部の製造網が長期にわたり麻痺する。",
    desc_en: "The world's largest hydroelectric dam is breached. 22.5 GW of power is lost, the lower Yangtze floods, and central China's manufacturing network is paralyzed for years.",
    src_note: "CTG Corp/IEA",
  },
  {
    id: "energy-salar-atacama", cat: "energy", cc: "CL",
    name_ja: "アタカマ塩湖リチウム鉱床", name_en: "Salar de Atacama Lithium",
    lat: -23.5, lng: -68.25, r_km: 18,
    flow_busd: 6, recovery_mo: 15,
    stat_ja: "世界有数のリチウム塩湖", stat_en: "top lithium salar · Atacama",
    deps: { CN: 0.4, KR: 0.2, JP: 0.1, US: 0.05 },
    desc_ja: "世界有数のリチウム塩湖が操業停止。電池向けリチウム供給が細り、中韓日の正極材とEV量産計画が同時に後退する。",
    desc_en: "One of the world's top lithium salars halts. Battery-grade lithium supply thins, setting back cathode output and EV production plans in China, Korea, and Japan.",
    src_note: "USGS/SQM reports",
  },
  {
    id: "energy-bayan-obo", cat: "energy", cc: "CN",
    name_ja: "白雲鄂博レアアース鉱床", name_en: "Bayan Obo Rare Earths",
    lat: 41.78, lng: 109.97, r_km: 15,
    flow_busd: 5, recovery_mo: 18,
    stat_ja: "世界最大の希土類鉱床", stat_en: "world's largest REE deposit",
    deps: { JP: 0.25, US: 0.2, KR: 0.1, DE: 0.1 },
    desc_ja: "世界最大の希土類鉱床が消失。磁石用レアアースの原料供給が断たれ、日米欧のモーター・防衛・風力の生産が広範に停滞する。",
    desc_en: "The world's largest rare-earth deposit is destroyed. Feedstock for magnet rare earths is cut, broadly stalling motor, defense, and wind-turbine output in Japan, the US, and Europe.",
    src_note: "USGS/company reports",
  },
  {
    id: "energy-beylikova", cat: "energy", cc: "TR",
    name_ja: "ベイリコヴァ レアアース鉱床(トルコ)", name_en: "Beylikova Rare Earths (Türkiye)",
    lat: 39.57, lng: 31.95, r_km: 10,
    flow_busd: 5, recovery_mo: 30,
    stat_ja: "推定6.9億t · 世界級REE埋蔵", stat_en: "est. 694Mt · world-class REE",
    deps: { DE: 0.2, US: 0.15, JP: 0.1, KR: 0.05 },
    desc_ja: "中国外では最大級とされるレアアース鉱床が失われる。非中国系の磁石材料サプライチェーン構想が土台から崩れ、欧米日の供給多角化が年単位で後退する。",
    desc_en: "One of the largest rare-earth deposits outside China is lost. Non-Chinese magnet-material supply-chain plans collapse at the foundation, setting back Western and Japanese diversification by years.",
    src_note: "Eti Maden announcements/USGS",
  },
  {
    id: "energy-eshidiya", cat: "energy", cc: "SA",
    name_ja: "エシディヤ リン鉱山(ヨルダン)", name_en: "Eshidiya Phosphate Mines (Jordan)",
    lat: 29.95, lng: 36.2, r_km: 14,
    flow_busd: 3, recovery_mo: 18,
    stat_ja: "リン鉱石 年900万t級", stat_en: "~9Mt/yr phosphate rock",
    deps: { IN: 0.35, ID: 0.1, BD: 0.08, BR: 0.08 },
    desc_ja: "ヨルダン南部の主要リン鉱区が操業停止。肥料原料の輸出が断たれ、インド亜大陸の肥料価格と食料生産コストに直撃する。",
    desc_en: "Southern Jordan's main phosphate district halts. Fertilizer feedstock exports are cut, hitting fertilizer prices and food-production costs across the Indian subcontinent.",
    src_note: "JPMC annual reports/USGS",
  },
  {
    id: "energy-waad-al-shamal", cat: "energy", cc: "SA",
    name_ja: "ワアド・アルシャマール リン鉱業都市(サウジ北部)", name_en: "Wa'ad Al Shamal Phosphate City (N. Saudi)",
    lat: 31.68, lng: 38.65, r_km: 16,
    flow_busd: 4, recovery_mo: 20,
    stat_ja: "リン酸肥料 統合生産拠点", stat_en: "integrated phosphate complex",
    deps: { IN: 0.35, BD: 0.08, BR: 0.1, ID: 0.06 },
    desc_ja: "サウジ北部の統合リン鉱業都市が壊滅。世界の肥料供給の新たな柱が失われ、穀物生産国の作付けコストが跳ね上がる。",
    desc_en: "Saudi Arabia's northern integrated phosphate city is destroyed. A new pillar of world fertilizer supply disappears, and planting costs jump across grain-producing nations.",
    src_note: "Ma'aden reports/USGS",
  },

  // ---- choke · 海上チョークポイント ----
  {
    id: "choke-malacca", cat: "choke", cc: "SG",
    name_ja: "マラッカ・シンガポール海峡", name_en: "Malacca–Singapore Strait",
    lat: 1.18, lng: 103.7, r_km: 20,
    flow_busd: 3500, recovery_mo: 2,
    stat_ja: "年9万隻・世界貿易の約3割が通過", stat_en: "94k ships/yr · ~30% world trade",
    deps: { CN: 0.3, JP: 0.12, KR: 0.08, IN: 0.06, TH: 0.04 },
    desc_ja: "アジア最短航路のフィリップス水道が航行不能となり、年9万隻分の通航がスンダ・ロンボク海峡へ迂回。中国・日韓向け原油と欧州向けコンテナが数日〜数週間遅延し、戦争保険料の急騰が海運コストを押し上げる。",
    desc_en: "The Phillips Channel bottleneck becomes unnavigable, diverting 94,000 annual transits through the Sunda and Lombok straits. Crude bound for China, Japan and Korea and Europe-bound containers slip days to weeks as war-risk premiums surge freight costs.",
    src_note: "UNCTAD/Lloyd's List 2023",
  },
  {
    id: "choke-taiwan-strait", cat: "choke", cc: "TW",
    name_ja: "台湾海峡", name_en: "Taiwan Strait",
    lat: 24.6, lng: 119.6, r_km: 50,
    flow_busd: 2400, recovery_mo: 2,
    stat_ja: "年2.4兆ドル・海上貿易の2割超", stat_en: "$2.4T goods/yr · >20% sea trade",
    deps: { CN: 0.3, JP: 0.15, KR: 0.12, US: 0.08 },
    desc_ja: "世界貿易の2割超が通る海峡が航行不能となり、船舶は台湾東方のフィリピン海側へ迂回。戦争保険料の急騰が運賃を押し上げ、中国・日韓の港湾と半導体関連物流が数週間単位で混乱する。",
    desc_en: "The strait carrying over a fifth of world trade becomes unnavigable, pushing shipping east of Taiwan into the Philippine Sea. War-risk premiums drive freight rates up sharply, disrupting Chinese, Japanese and Korean ports and semiconductor logistics for weeks.",
    src_note: "CSIS transit estimate 2022",
  },
  {
    id: "choke-suez", cat: "choke", cc: "EG",
    name_ja: "スエズ運河", name_en: "Suez Canal",
    lat: 30.45, lng: 32.35, r_km: 20,
    flow_busd: 1000, recovery_mo: 12,
    stat_ja: "世界貿易の12%・年2.4万隻通航", stat_en: "12% of world trade · 24k transits",
    deps: { CN: 0.2, DE: 0.1, NL: 0.08, IT: 0.06, GB: 0.05, FR: 0.05 },
    desc_ja: "運河の航路と護岸構造が破壊され、アジア〜欧州航路は喜望峰回りに全面転換。輸送日数は10日以上延び、欧州の小売・製造在庫が先に枯渇し、エジプトは年約90億ドルの通航料収入を失う。",
    desc_en: "The canal channel and embankments are destroyed, forcing all Asia-Europe traffic around the Cape of Good Hope. Voyages lengthen by 10+ days, European retail and manufacturing inventories run dry first, and Egypt loses roughly $9B a year in transit tolls.",
    src_note: "SCA annual report / Lloyd's List 2021",
  },
  {
    id: "choke-bab-el-mandeb", cat: "choke", cc: "SA",
    name_ja: "バブ・エル・マンデブ海峡", name_en: "Bab el-Mandeb Strait",
    lat: 12.57, lng: 43.3, r_km: 25,
    flow_busd: 900, recovery_mo: 3,
    stat_ja: "日量620万バレル・スエズと直列", stat_en: "6.2M bbl/d oil · gateway to Suez",
    deps: { CN: 0.18, DE: 0.08, NL: 0.07, IT: 0.06, EG: 0.06, FR: 0.05 },
    desc_ja: "紅海南端の隘路が封鎖され、直列するスエズ航路が事実上連動して停止。アジア〜欧州航路は喜望峰回りへ転換し、欧州向け燃料・消費財の到着が数週間遅れ、エジプトの通航料収入も直撃を受ける。",
    desc_en: "The Red Sea's southern gate closes, effectively shutting the Suez route in tandem. Asia-Europe traffic diverts around the Cape of Good Hope, delaying Europe-bound fuel and consumer goods by weeks and gutting Egypt's canal toll revenue.",
    src_note: "EIA World Oil Transit Chokepoints 2023",
  },
  {
    id: "choke-dover", cat: "choke", cc: "GB",
    name_ja: "ドーバー海峡", name_en: "Strait of Dover",
    lat: 51.01, lng: 1.45, r_km: 20,
    flow_busd: 800, recovery_mo: 2,
    stat_ja: "1日500隻超・世界最繁忙の海峡", stat_en: "500+ ships/day · world's busiest",
    deps: { NL: 0.2, DE: 0.15, BE: 0.12, FR: 0.1, PL: 0.05 },
    desc_ja: "世界最繁忙の海峡が閉鎖され、ロッテルダム・アントワープ・ハンブルクへ向かう船舶はスコットランド北回りへ迂回。北海主要港の物流が滞り、英仏間のフェリー輸送も停止して英国の食料・生活物資輸入が最初に逼迫する。",
    desc_en: "The world's busiest shipping lane closes; vessels bound for Rotterdam, Antwerp and Hamburg divert north around Scotland. North Sea port logistics stall, cross-Channel ferry traffic halts, and UK food and consumer imports tighten first.",
    src_note: "UK MCA / Lloyd's List",
  },
  {
    id: "choke-hormuz", cat: "choke", cc: "IR",
    name_ja: "ホルムズ海峡", name_en: "Strait of Hormuz",
    lat: 26.57, lng: 56.52, r_km: 40,
    flow_busd: 700, recovery_mo: 4,
    stat_ja: "日量2,100万バレル・海上石油の3割", stat_en: "21M bbl/day · 30% seaborne oil",
    deps: { CN: 0.25, IN: 0.15, JP: 0.12, KR: 0.1 },
    desc_ja: "ペルシャ湾唯一の外洋出口が封鎖され、湾岸産原油・LNGの海上輸出が代替航路なく停止。パイプライン迂回は容量が限られ、中国・インド・日韓の調達が即座に逼迫し、原油価格の急騰が世界に連鎖する。",
    desc_en: "The Persian Gulf's only maritime exit closes; Gulf crude and LNG exports halt with no sea alternative and only limited pipeline bypass. China, India, Japan and Korea face immediate supply shortfalls as oil prices spike worldwide.",
    src_note: "EIA World Oil Transit Chokepoints 2023",
  },
  {
    id: "choke-panama", cat: "choke", cc: "CO",
    name_ja: "パナマ運河", name_en: "Panama Canal",
    lat: 9.12, lng: -79.7, r_km: 15,
    flow_busd: 300, recovery_mo: 12,
    stat_ja: "年1.3万隻・海上貿易の5%", stat_en: "13k transits/yr · 5% sea trade",
    deps: { US: 0.4, CN: 0.12, JP: 0.06, CL: 0.05, KR: 0.04 },
    desc_ja: "閘門システムが破壊され、太平洋と大西洋を結ぶ近道が消失。米東岸〜アジアの貨物はホーン岬回りか米国横断の陸橋輸送へ転換し、穀物・LNG輸出と米小売サプライチェーンが最初に打撃を受ける。",
    desc_en: "The lock system is destroyed, erasing the Pacific-Atlantic shortcut. US East Coast-Asia cargo diverts around Cape Horn or onto the US land bridge; grain and LNG exports and American retail supply chains take the first hit.",
    src_note: "Panama Canal Authority FY2023",
  },
  {
    id: "choke-bosporus", cat: "choke", cc: "TR",
    name_ja: "ボスポラス海峡", name_en: "Bosporus Strait",
    lat: 41.09, lng: 29.06, r_km: 15,
    flow_busd: 200, recovery_mo: 4,
    stat_ja: "年4.5万隻・黒海唯一の出口", stat_en: "45k ships/yr · only Black Sea exit",
    deps: { RU: 0.35, EG: 0.08, CN: 0.08, IT: 0.05, RO: 0.04 },
    desc_ja: "黒海唯一の外洋出口が閉鎖。ロシア産原油はバルト海経由へ、穀物はドナウ川と鉄道へ迂回するが容量は遠く及ばず、エジプトなど黒海産穀物への依存国と沿岸経済が最初に締め付けられる。",
    desc_en: "The Black Sea's only ocean exit closes. Russian crude reroutes via Baltic ports and grain shifts to the Danube and rail, but capacity falls far short; grain-import states like Egypt and the Black Sea littoral economies are squeezed first.",
    src_note: "UNCTAD / Turkish Straits reports",
  },
];
